load("@crates//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

exports_files(["Cargo.toml"])

rust_library(
    name = "tau-edit",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    compile_data = glob([
        "prompts/*.md",
        "grammars/*.lark",
    ]),
    crate_name = "tau_edit",
    edition = "2024",
    proc_macro_deps = all_crate_deps(proc_macro = True),
    version = "18.1.5",
    deps = all_crate_deps(normal = True) + [
        "//crates/tau-ast",
        "//crates/tau-diff",
        "//crates/tau-walker",
    ],
)

rust_test(
    name = "tau-edit_test",
    compile_data = glob(["tests/fixtures/notebooks/*"]),
    crate = ":tau-edit",
    data = glob(["tests/fixtures/**"]),
    edition = "2024",
    proc_macro_deps = all_crate_deps(proc_macro_dev = True),
    deps = all_crate_deps(normal_dev = True),
)
